# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9cfb8015-7ae1-47ea-813f-766eda9283f7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-076abcbe-24fc-400f-9f8c-414f453319fd".device = "/dev/disk/by-uuid/076abcbe-24fc-400f-9f8c-414f453319fd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2296-77BE";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/48444e2c-e8f0-4a45-bfea-99ed67fb9ac7";
      fsType = "btrfs";
      options = [ "noatime" "lazytime" "compress=zstd" ];
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/999658fe-a8e0-4f12-9b40-f24932a303d6";
      fsType = "btrfs";
      options = [ "noatime" "lazytime" "compress=zstd" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/bbc5a71c-af08-4d0a-a84d-509ca06f0356";
      fsType = "btrfs";
      options = [ "noatime" "lazytime" "compress=zstd" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u6.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
